[package]
name = "trace-merge"
version.workspace = true
edition.workspace = true

[[bin]]
name = "trace-merge"
path = "src/main.rs"

[dependencies]
trace-db = { workspace = true }
anyhow.workspace = true
clap.workspace = true
rusqlite.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
