[package]
name = "trace-analysis"
version.workspace = true
edition.workspace = true

[dependencies]
trace-ir = { workspace = true }
indexmap.workspace = true
petgraph.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
serde.workspace = true
toml.workspace = true
z3 = { workspace = true, optional = true }

[features]
default = []
smt = ["dep:z3"]

