[package]
name = "trace-preproc"
version.workspace = true
edition.workspace = true

[features]
default = []
smt = ["dep:z3"]

[dependencies]
trace-ir = { workspace = true }
anyhow.workspace = true
indexmap.workspace = true
regex.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
z3 = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true

