[package]
name = "trace-preproc"
version.workspace = true
edition.workspace = true

[dependencies]
trace-ir = { workspace = true }
anyhow.workspace = true
indexmap.workspace = true
regex.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
